/// Accreditation AI Agent screen.
///
/// Lets users ask questions in natural language about the documents stored in
/// the Accreditation folder. Answers are generated by the Gemini API on the
/// server and returned together with clickable source PDF links.
library;

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../../core/api/chat_api_service.dart';
import '../../../shared/widgets/authenticated_image.dart';
import '../../../shared/theme/app_theme.dart';
import '../data/accreditation_agent_response.dart';

class AccreditationAgentScreen extends ConsumerStatefulWidget {
  const AccreditationAgentScreen({super.key});

  @override
  ConsumerState<AccreditationAgentScreen> createState() =>
      _AccreditationAgentScreenState();
}

class _AccreditationAgentScreenState
    extends ConsumerState<AccreditationAgentScreen> {
  final TextEditingController _questionController = TextEditingController();
  final ScrollController _scrollController = ScrollController();

  bool _isLoading = false;
  String? _answer;
  List<AccreditationFile> _relevantFiles = [];
  String? _errorMessage;

  @override
  void dispose() {
    _questionController.dispose();
    _scrollController.dispose();
    super.dispose();
  }

  Future<void> _sendQuestion() async {
    final question = _questionController.text.trim();
    if (question.isEmpty) return;

    setState(() {
      _isLoading = true;
      _answer = null;
      _relevantFiles = [];
      _errorMessage = null;
    });

    try {
      final api = ref.read(chatApiServiceProvider);
      final response = await api.askAccreditationAgent(question);
      if (!mounted) return;
      setState(() {
        _answer = response.answer;
        _relevantFiles = response.relevantFiles;
        _isLoading = false;
      });
      // Scroll to the answer after it renders.
      WidgetsBinding.instance.addPostFrameCallback((_) {
        if (_scrollController.hasClients) {
          _scrollController.animateTo(
            _scrollController.position.maxScrollExtent,
            duration: const Duration(milliseconds: 400),
            curve: Curves.easeOut,
          );
        }
      });
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _errorMessage = e.toString().replaceFirst(RegExp(r'^ApiException: '), '');
        _isLoading = false;
      });
    }
  }

  Future<void> _openFile(AccreditationFile file) async {
    final resolved = resolveToAbsoluteUrl(file.url);
    final uri = Uri.tryParse(resolved);
    if (uri == null) return;
    if (!await launchUrl(uri, mode: LaunchMode.externalApplication)) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('לא ניתן לפתוח את הקובץ: ${file.name}')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.rtl,
      child: Scaffold(
        appBar: AppBar(
          title: const Text('סוכן אקרדיטציה'),
          backgroundColor: AppColors.primary,
          foregroundColor: Colors.white,
        ),
        body: Column(
          children: [
            Expanded(
              child: SingleChildScrollView(
                controller: _scrollController,
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    _buildIntroCard(),
                    if (_isLoading) _buildLoadingIndicator(),
                    if (_errorMessage != null) _buildErrorCard(),
                    if (_answer != null) _buildAnswerCard(),
                    if (_relevantFiles.isNotEmpty) _buildFilesSection(),
                    const SizedBox(height: 16),
                  ],
                ),
              ),
            ),
            _buildInputBar(),
          ],
        ),
      ),
    );
  }

  Widget _buildIntroCard() {
    return Card(
      margin: const EdgeInsets.only(bottom: 16),
      color: AppColors.primaryLight.withAlpha(30),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: const Padding(
        padding: EdgeInsets.all(16),
        child: Row(
          children: [
            Icon(Icons.auto_awesome, color: AppColors.primary),
            SizedBox(width: 12),
            Expanded(
              child: Text(
                'שאל שאלה בשפה חופשית על מסמכי האקרדיטציה.\n'
                'הסוכן יענה ויצרף את הקבצים הרלוונטיים.',
                style: TextStyle(fontSize: 13),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildLoadingIndicator() {
    return const Padding(
      padding: EdgeInsets.symmetric(vertical: 32),
      child: Center(
        child: Column(
          children: [
            CircularProgressIndicator(),
            SizedBox(height: 12),
            Text('מעבד את השאלה...', style: TextStyle(color: Colors.grey)),
          ],
        ),
      ),
    );
  }

  Widget _buildErrorCard() {
    return Card(
      margin: const EdgeInsets.only(bottom: 16),
      color: AppColors.error.withAlpha(20),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Icon(Icons.error_outline, color: AppColors.error),
            const SizedBox(width: 12),
            Expanded(
              child: Text(
                _errorMessage ?? '',
                style: const TextStyle(color: AppColors.error),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildAnswerCard() {
    return Card(
      margin: const EdgeInsets.only(bottom: 16),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Row(
              children: [
                Icon(Icons.smart_toy_outlined, color: AppColors.primary, size: 20),
                SizedBox(width: 8),
                Text(
                  'תשובת הסוכן',
                  style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14),
                ),
              ],
            ),
            const SizedBox(height: 12),
            SelectableText(
              _answer ?? '',
              style: const TextStyle(fontSize: 14, height: 1.6),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildFilesSection() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        const Text(
          'קבצים רלוונטיים',
          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 13),
        ),
        const SizedBox(height: 8),
        ..._relevantFiles.map(_buildFileTile),
      ],
    );
  }

  Widget _buildFileTile(AccreditationFile file) {
    return Card(
      margin: const EdgeInsets.only(bottom: 8),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
      child: ListTile(
        leading: const Icon(Icons.picture_as_pdf, color: Colors.red),
        title: Text(
          file.name,
          style: const TextStyle(fontSize: 13),
          maxLines: 2,
          overflow: TextOverflow.ellipsis,
        ),
        trailing: const Icon(Icons.open_in_new, size: 18, color: Colors.grey),
        onTap: () => _openFile(file),
      ),
    );
  }

  Widget _buildInputBar() {
    return Container(
      padding: const EdgeInsets.fromLTRB(12, 8, 12, 12),
      decoration: BoxDecoration(
        color: Theme.of(context).scaffoldBackgroundColor,
        boxShadow: [
          BoxShadow(
            color: Colors.black.withAlpha(25),
            blurRadius: 6,
            offset: const Offset(0, -2),
          ),
        ],
      ),
      child: SafeArea(
        top: false,
        child: Row(
          children: [
            Expanded(
              child: TextField(
                controller: _questionController,
                textDirection: TextDirection.rtl,
                maxLines: 4,
                minLines: 1,
                textInputAction: TextInputAction.send,
                onSubmitted: (_) => _isLoading ? null : _sendQuestion(),
                decoration: InputDecoration(
                  hintText: 'הקלד שאלה על מסמכי האקרדיטציה...',
                  hintTextDirection: TextDirection.rtl,
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(24),
                    borderSide: BorderSide(color: Colors.grey.shade300),
                  ),
                  contentPadding: const EdgeInsets.symmetric(
                    horizontal: 16,
                    vertical: 10,
                  ),
                ),
              ),
            ),
            const SizedBox(width: 8),
            _isLoading
                ? const SizedBox(
                    width: 44,
                    height: 44,
                    child: Padding(
                      padding: EdgeInsets.all(10),
                      child: CircularProgressIndicator(strokeWidth: 2),
                    ),
                  )
                : IconButton(
                    icon: const Icon(Icons.send, color: AppColors.primary),
                    tooltip: 'שלח',
                    onPressed: _sendQuestion,
                  ),
          ],
        ),
      ),
    );
  }
}
